# Change these first
owner: arco-link # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: development-app
    url: https://dev-app.reviewtable.ru/api/health
  - name: development-backend
    url: https://dev-backend.reviewtable.ru/health
  - name: development-ya-business-client
    url: https://dev-ya-business-client.reviewtable.ru/health

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
